server:
  port: 8080

spring:
  application:
    name: product-review
datasource:
  url: jdbc:h2:productreview:productreviewdb
  driverClassName: org.h2.Driver
  username: sa
  password:
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
h2:
  console:
    enabled: true